/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class MIDINetworkHost, NSMutableDictionary, NSMutableSet, NSString;

#pragma mark Named Structures

struct ContactOrConnectionSet {
    _Bool mItemsAreConnections;
    NSMutableSet *mSet;
};

struct OpaqueMIDIEndpoint;

struct OpaqueMIDIEntity;

struct _MIDINetworkConnectionImpl {
    MIDINetworkHost *_field1;
};

struct _MIDINetworkHostImpl {
    NSString *_field1;
    NSString *_field2;
    unsigned int _field3;
    NSString *_field4;
    NSString *_field5;
};

struct _MIDINetworkSessionImpl {
    struct OpaqueMIDIEntity *_field1;
    struct OpaqueMIDIEndpoint *_field2;
    struct OpaqueMIDIEndpoint *_field3;
    NSString *_field4;
    NSMutableDictionary *_field5;
    struct ContactOrConnectionSet _field6;
};

