/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPPipelineJPEGDecoder : NSObject
{
    struct StackItem *stackTopBGRA;
    struct StackItem *stackTop420;
    struct StackItem *stackTopJPEG;
    struct dispatch_queue_s *stackQueueBGRA;
    struct dispatch_queue_s *stackQueue420;
    struct dispatch_queue_s *stackQueueJPEG;
    struct __CFDictionary *acceleratorOptions;
    struct __CFDictionary *surfaceBGRAOptions;
    struct CGSize imageSize;
    unsigned int requestedImageCount;
    int currentBGRASurfaceCount;
    unsigned int maxJPEGSize;
}

+ (struct __IOSurfaceAccelerator *)_popSurfaceAccelerator;
+ (void)_pushSurfaceAccelerator:(struct __IOSurfaceAccelerator *)arg1;
+ (struct __IOSurfaceAccelerator *)_createAccelerator;
+ (struct dispatch_queue_s *)_stackQueueTransferSession;
@property unsigned int maxJPEGSize; // @synthesize maxJPEGSize;
- (void)_receivedMemoryWarning:(id)arg1;
- (void)_decodeJPEG:(id)arg1 withInputSurface:(struct __IOSurface *)arg2 toIOSurface:(struct __IOSurface *)arg3;
- (id)_newImageFrom420Surface:(struct __IOSurface *)arg1;
- (void)_pushBGRASurface:(struct __IOSurface *)arg1;
- (struct __IOSurface *)_popBGRASurface;
- (void)_pushJPEGSurface:(struct __IOSurface *)arg1;
- (struct __IOSurface *)_popJPEGSurfaceOfSize:(unsigned int)arg1;
- (void)_push420Surface:(struct __IOSurface *)arg1;
- (struct __IOSurface *)_pop420Surface;
- (void)_removeBGRASurface;
- (struct __IOSurface *)_createBGRASurface;
- (struct __IOSurface *)_createJPEGSurface;
- (struct __IOSurface *)_create420Surface;
- (void)dealloc;
- (id)newImageFromJPEGData:(id)arg1;
- (id)newImageFrom420Data:(id)arg1;
- (id)initWithSize:(struct CGSize)arg1 cachedCount:(int)arg2;

@end

