/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreFoundation/NSObject.h>

#import "NSXPCObject-Protocol.h"

@class NSMutableArray, NSXPCConnection, Protocol;

@interface __NSXPCObjCServerClient : NSObject <NSXPCObject>
{
    NSXPCConnection *_peer;
    Protocol *_protocol;
    id _instance;
    NSMutableArray *_invalidHandlers;
    int _started;
    int _invalid;
}

+ (id)clientWithXPCConnection:(struct _xpc_connection_s *)arg1 protocol:(id)arg2 instance:(id)arg3;
- (void)start;
- (void)addInvalidationHandler:(id)arg1;
- (void)invalidate;
- (void)__invalidate;
- (void)dealloc;

@end

