/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreFoundation/NSObject.h>

#import "NSXPCObject-Protocol.h"

@class NSMutableArray, NSString;

@interface NSXPCServer : NSObject <NSXPCObject>
{
    struct _xpc_connection_s *_conn;
    int _lock;
    struct dispatch_queue_s *_dq;
    NSString *_serviceName;
    id _makeNewClient;
    NSMutableArray *_clients;
    NSMutableArray *_invalidHandlers;
    int _started;
    int _invalid;
    BOOL _priv;
}

- (void *)encodeToNewXPCObject;
- (id)allClients;
- (void)start;
- (void)addInvalidationHandler:(id)arg1;
- (void)invalidate;
- (void)__invalidate;
- (void)setPrivileged:(BOOL)arg1;
@property(nonatomic) struct dispatch_queue_s *dispatchQueue; // @dynamic dispatchQueue;
@property(copy) id makeNewClient; // @dynamic makeNewClient;
@property(copy) NSString *serviceName; // @dynamic serviceName;
- (void)dealloc;
- (id)init;

@end

