/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreFoundation/NSObject.h>

#import "NSXPCObject-Protocol.h"

@class NSMutableArray, NSString;

@interface NSXPCConnection : NSObject <NSXPCObject>
{
    struct _xpc_connection_s *_conn;
    struct _xpc_connection_s *_sconn;
    int _lock;
    struct dispatch_queue_s *_dq;
    struct dispatch_group_s *_dgroup;
    NSString *_serviceName;
    id _handleMessage;
    long long _mseqno;
    NSMutableArray *_invalidHandlers;
    int _started;
    int _invalid;
    int _flavor;
}

- (id)initWithXPCObject:(void *)arg1;
- (void *)encodeToNewXPCObject;
- (void)sendMessage:(void *)arg1 waitForAck:(BOOL)arg2;
- (void)sendMessage:(void *)arg1 waitForSend:(BOOL)arg2;
- (void)start;
- (void)addInvalidationHandler:(id)arg1;
- (void)invalidate;
- (void)__invalidate;
@property(nonatomic) struct dispatch_queue_s *dispatchQueue; // @dynamic dispatchQueue;
@property(copy) id handleMessage; // @dynamic handleMessage;
@property(readonly, nonatomic) struct _xpc_connection_s *XPCConnection; // @dynamic XPCConnection;
@property(readonly) NSString *serviceName; // @dynamic serviceName;
- (id)initWithPeerConnection:(struct _xpc_connection_s *)arg1;
- (id)initWithReceivedConnection:(struct _xpc_connection_s *)arg1;
- (id)initWithServiceName:(id)arg1 privileged:(BOOL)arg2;
- (void)dealloc;
- (id)initWithXPCConnection:(struct _xpc_connection_s *)arg1 type:(int)arg2;

@end

