/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class EAGLSharegroup;

@interface EAGLContext : NSObject
{
    struct _EAGLContextPrivate *_private;
}

+ (BOOL)setCurrentContext:(id)arg1;
+ (id)currentContext;
- (id)initWithAPI:(unsigned int)arg1;
- (id)initWithAPI:(unsigned int)arg1 sharedWithCompute:(BOOL)arg2;
- (id)initWithAPI:(unsigned int)arg1 sharegroup:(id)arg2;
- (id)initWithAPI:(unsigned int)arg1 properties:(id)arg2;
- (void)dealloc;
@property(readonly) unsigned int API;
@property(readonly) EAGLSharegroup *sharegroup;
- (BOOL)renderbufferStorage:(unsigned int)arg1 fromDrawable:(id)arg2;
- (BOOL)presentRenderbuffer:(unsigned int)arg1;
- (BOOL)attachImage:(unsigned int)arg1 toCoreSurface:(struct __IOSurface *)arg2 invertedRender:(BOOL)arg3;
- (BOOL)texImageIOSurface:(struct __IOSurface *)arg1 target:(unsigned int)arg2 internalFormat:(unsigned int)arg3 width:(unsigned int)arg4 height:(unsigned int)arg5 format:(unsigned int)arg6 type:(unsigned int)arg7 plane:(unsigned int)arg8 invert:(BOOL)arg9;
- (void)sendNotification:(unsigned int)arg1 forTransaction:(unsigned int)arg2 onLayer:(unsigned int)arg3;
- (void)swapNotification:(struct __IOMobileFramebuffer *)arg1 forTransaction:(unsigned int)arg2 onLayer:(unsigned int)arg3;
- (unsigned int)setParameter:(unsigned int)arg1 to:(int *)arg2;
- (unsigned int)getParameter:(unsigned int)arg1 to:(int *)arg2;
- (struct EAGLMacroContext *)GetMacroContextPrivate;

@end

